Repository LucaNerlich/m10z, pull requests merged in 2023-04, with the labels that each got.

#19 PC Bau Fotostory
  blog/authors.yml
  blog/tech/2023-04-08-pc-upgrade-luca-edition/02-mb.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/07-gpu.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/16-case.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/24-mb.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/25-mb.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/26-mb.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/27-desk.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/33-cpu.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/35-mb.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/37-ssd.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/38-mb.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/39-mb.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/40-ssd.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/41-ssd.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/42-ssd.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/44-cooler.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/45-cooler.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/46-cooler.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/47-cooler.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/48-cooler.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/49-cooler.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/5-cooler.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/50-cooler.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/51-cooler.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/52-cooler.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/53-cooler.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/54-case.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/55-case.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/56-psu.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/57-cabel.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/59-psu.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/60-psu.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/61-boot.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/63-terabyte.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/ff.jpg
  blog/tech/2023-04-08-pc-upgrade-luca-edition/index.mdx
  blog/tech/2023-04-08-pc-upgrade-luca-edition/sd.png
  package-lock.json
  src/styles/theme.css
Labels: release candidate, scheduled

#71 Virtuelle Verse #2
  blog/articles/poems/2023-04-08-virtuelle-verse.md
  blog/authors.yml
Labels: release candidate, scheduled, merge-schedule-failed

#73 Once we were Gamer #1
  blog/articles/poems/2023-03-25-virtuelle-verse.md
  blog/articles/poems/2023-04-08-virtuelle-verse.md
  blog/articles/reviews/2023-03-20-diablo4-beta/index.mdx
  blog/authors.yml
  blog/podcasts/2023-03-15-m10z-1.md
  blog/podcasts/2023-03-31-audio-player-test.mdx
  blog/podcasts/2023-04-01-fundbuero-1.mdx
  blog/podcasts/2023-04-09-owwg-1.mdx
  blog/tech/2023-04-08-pc-upgrade-luca-edition/index.mdx
  package-lock.json
  package.json
  static/audiofeed.xml
  static/img/OWWG_Logo_3000x3000.jpg
  static/img/tech/terabyte.jpg
Labels: work in progress, scheduled
