Repository LucaNerlich/m10z, pull requests merged in 2023-03, with the labels that each got.

#1 added example audio rss feed
  static/audiofeed.xml
Labels: help wanted

#20 17 pyre story redigieren
  blog/articles/reviews/2018-12-18-pyre-wertschaetzung/index.mdx
Labels: release candidate

#26 M10Z Logos
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Favicon.svg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten.ai
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten.pdf
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Instagram Post.jpg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Instagram Post.png
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Instagram Post.svg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Instagram Profil.jpg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Instagram Profil.png
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Instagram Profil.svg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Twitter Profil.jpg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Twitter Profil.png
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Twitter Profil.svg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Youtube Header.jpg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Youtube Header.png
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Youtube Header.svg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Youtube Profil.jpg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Youtube Profil.png
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Dark Youtube Profil.svg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Instagram Post.jpg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Instagram Post.png
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Instagram Post.svg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Instagram Profil.jpg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Instagram Profil.png
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Instagram Profil.svg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Twitter Profil.jpg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Twitter Profil.png
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Twitter Profil.svg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Youtube Header.jpg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Youtube Header.png
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Youtube Header.svg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Youtube Profil.jpg
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Youtube Profil.png
  resources/M10Z_Logo/Logo Varianten/M10Z_Logo_Varianten_Youtube Profil.svg
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Favicon.svg
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten.ai
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten.pdf
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Instagram Post.jpg
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Instagram Post.png
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Instagram Post.svg
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Instagram Profil.jpg
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Instagram Profil.png
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Instagram Profil.svg
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Twitter Profil.jpg
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Twitter Profil.png
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Twitter Profil.svg
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Youtube Header.jpg
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Youtube Header.png
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Youtube Header.svg
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Youtube Profil.jpg
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Youtube Profil.png
  resources/M10Z_Logo/TV Logo Varianten/M10Z_TV_Logo_Varianten_Youtube Profil.svg
Labels: enhancement

#31 Update hello.js
  .gitignore
  src/pages/hello.js
Labels: release candidate

#10 wer wir sind page
  .gitignore
  docusaurus.config.js
  src/pages/hello.js
Labels: release candidate

#9 imprint and privacy
  docusaurus.config.js
  src/pages/hello.js
  src/pages/imprint.js
  src/pages/privacy.js
  src/styles/theme.css
Labels: release candidate

#32 Merge schedule
  .github/workflows/merge-schedule.yml
Labels: release candidate, scheduled

#12 article and podcast template
  templates/announcement.mdx
  templates/article.mdx
  templates/podcast.mdx
  templates/video.mdx
Labels: help wanted

#39 Fußzeile Typos korrigiert
  docusaurus.config.js
Labels: release candidate

#40 React audio player
  blog/podcasts/2023-03-31-audio-player-test.mdx
  package-lock.json
  package.json
  templates/podcast.mdx
Labels: enhancement

#52 Create 2023-04-01-fundbuero-1
  blog/authors.yml
  blog/podcasts/2023-04-01-fundbuero-1.mdx
  docusaurus.config.js
Labels: release candidate, scheduled

#15 Release Diablo 4 Post
  blog/articles/reviews/2023-03-20-diablo4-beta/index.mdx
Labels: release candidate, scheduled

#36 M10Z Launch Post
  blog/articles/announcement/2023-04-01-welcome-to-m10z/header.jpg
  blog/articles/announcement/2023-04-01-welcome-to-m10z/index.mdx
  blog/articles/reviews/2018-12-18-pyre-wertschaetzung/index.mdx
Labels: release candidate, scheduled, merge-schedule-failed

#30 Create Virtuelle Verse 1
  blog/articles/poems/2023-03-25-virtuelle-verse.md
Labels: release candidate, scheduled
