Repository LucaNerlich/m10z, pull requests merged in 2024-12, with the labels that each got.

#226 Xmas
  blog/podcasts/specials/2024-12-24-xmas2024.mdx
  static/audiofeed.yaml
Labels: podcast

#214 c10z-8
  .vale.ini
  blog/articles/reviews/2024-01-04-gothic-classic/index.mdx
  blog/articles/reviews/2024-01-23-c10z-1.mdx
  blog/articles/reviews/2024-02-11-c10z-2.mdx
  blog/articles/reviews/2024-02-25-c10z-3.mdx
  blog/articles/reviews/2024-03-09-c10z-4.mdx
  blog/articles/reviews/2024-03-31-c10z-5.mdx
  blog/articles/reviews/2024-09-23-c10z-6.mdx
  blog/articles/reviews/2024-12-01-c10z-7.mdx
  blog/articles/reviews/2024-12-28-c10z-8.mdx
  blog/articles/reviews/2025-02-01-c10z-8.mdx
  blog/articles/reviews/2025-02-01-c10z-9.mdx
  static/img/articles/schwingenschlag.jpg
  static/img/formate/c10z.jpg
  static/img/reviews/gothic.jpg
Labels: work in progress, text

#228 Fostering apocalypse telefxnmast
  blog/articles/kommentare/2023-04-23-love-letter-amd.mdx
  blog/articles/kommentare/2023-09-11-roleplay.mdx
  blog/articles/kommentare/2023-10-20-types-of-gamers.mdx
  blog/articles/kommentare/2024-01-21-hatred-kane-lynch-1.mdx
  blog/articles/kommentare/2024-01-21-hatred-kane-lynch-2.mdx
  blog/articles/kommentare/2024-01-21-hatred-kane-lynch-3.mdx
  blog/articles/kommentare/2024-01-21-hatred-kane-lynch-4.mdx
  blog/articles/kommentare/2024-02-07-old-but-gold.mdx
  blog/articles/kommentare/2024-07-20-a-plague-tale-requiem.mdx
  blog/articles/kommentare/2024-12-29-fostering-apocalypse.mdx
  src/styles/root.css
Labels: release candidate, text
