Repository LucaNerlich/m10z, pull requests merged in 2024-02, with the labels that each got.

#167 Filmspiel
  blog/articles/poems/2024-02-02-virtuelle-verse.md
Labels: release candidate, scheduled

#163 SP - RSS FEED GEN
  blog/articles/tech/2023-11-19-sunday-projects-transcription.mdx
  blog/articles/tech/2024-01-07-sunday-projects-ez-budget/index.mdx
  blog/articles/tech/2024-02-04-sunday-projects-rss-feed-gen.mdx
  generateAudioFeed.js
  src/pages/unsere-formate.tsx
  static/img/tech/sundayprojects/rssgen.jpg
  templates/rss-channel.xml
Labels: release candidate, scheduled, text

#165 Dgw234
  blog/podcasts/das-gesprochene-wort/2024-02-05-dgw-2.mdx
  src/pages/unsere-formate.tsx
  static/audiofeed.yaml
Labels: release candidate, podcast

#149 gina old-but-gold
  blog/articles/kommentare/2023-10-23-types-of-gamers.mdx
  blog/articles/kommentare/2024-02-07-old-but-gold.mdx
Labels: work in progress, text

#164 C10z 2
  blog/articles/reviews/2024-02-11-c10z-2.mdx
  blog/articles/reviews/2024-02-25-c10z-3.mdx
  blog/articles/reviews/2024-03-03-c10z-4.mdx
  package-lock.json
  package.json
Labels: release candidate, scheduled, text

#168 C10z 3
  blog/articles/reviews/2024-02-25-c10z-3.mdx
  blog/articles/reviews/2024-03-03-c10z-4.mdx
  blog/articles/reviews/2024-03-09-c10z-4.mdx
  blog/articles/reviews/2024-03-31-c10z-5.mdx
  package-lock.json
  package.json
Labels: release candidate, scheduled, text
